version: '3.7'
networks:
  backend:
volumes:
  home:
services:
  ood:
    build:
      context: .
      target: ood
    container_name: docker-with-slurm-ood
    hostname: ood
    ports:
      - 8080:80
    networks:
      - backend
    depends_on:
      - head
    volumes:
      - home:/home
      - ../common/example.yml:/etc/ood/config/clusters.d/example.yml
      - ../common/nginx_stage.yml:/etc/ood/config/nginx_stage.yml
      - ../common/logo.png:/var/www/ood/public/logo.png
      - ../common/logo-alt.png:/var/www/ood/public/logo-alt.png
      - ../common/logo-sm.png:/var/www/ood/public/logo-sm.png
      # Announcements
      - ../common/announcement.md:/etc/ood/config/announcements.d/announcement.md
      - ../common/announcement.yml:/etc/ood/config/announcements.d/announcement.yml
      # MOTD
      - ../common/motd.md:/etc/ood/config/motd.md
      # Job Composer template
      - ../common/job-template.yml:/etc/ood/config/apps/myjobs/templates/job-template.yml
      # Custom Error Page for Missing Home Directory
      - ../common/missing_home_directory.html:/etc/ood/config/pun/html/missing_home_directory.html
  head:
    build:
      context: .
      target: head
    container_name: docker-with-slurm-head
    hostname: head
    networks:
      - backend
    volumes:
      - home:/home
